cloudfoundry/bosh-openstack-cpi-release

- jobs/cpi/spec
I tried to use manifest from [bosh.io docs](http://bosh.io/docs/init-openstack.html), but I got an error that said that I didn't specified `nats.port` option. After some investigation I found out that the reason is that [bosh-director](https://github.com/cloudfoundry/bosh/blob/master/release/jobs/director/spec#L120) has a default value for this option, but [bosh-openstack-cpi-release doesn't](https://github.com/cloudfoundry-incubator/bosh-openstack-cpi-release/blob/master/jobs/cpi/spec#L85). This PR fixes it.
Thank you,
Alex L.
> Add default NATS port to spec file

- scripts/vendor_gems
Hey, everyone.
Not long ago I needed to update version of bosh_openstack_cpi gems. In order to do it I run `./script/vendor_gems` script. After I did it I've got a following error while trying to run this CPI with bosh-init:
```
Resolving dependencies...
Some gems seem to be missing from your vendor/cache directory.
Your Gemfile has no gem server sources. If you need gems that are not already on
your machine, add a line like this to your Gemfile:
source 'https://rubygems.org'
Could not find gem 'fog-core (>= 0) ruby', which is required by gem
'bosh_openstack_cpi (>= 0) ruby', in any of the sources.
```
After some investigation found a cause of error: I use bundler with version 1.9.1 to generate gems, but this release uses bundler 1.8.2, which has different dependency resolver. 
I've made …
> Restrict to run vendor_gems script with wrong version of bundler.

- src/bosh_openstack_cpi/docs/bosh_cpi.md
Links were still referring to images in the bosh core repo.
Replaced with relative links.
> Correct image links in bosh_cpi.md

- jobs/openstack_cpi/templates/cpi.erb
Hi,
without the `-r` option of the [`read`](http://linuxcommand.org/lc3_man_pages/readh.html) command, backslashes in JSON strings are interpreted as bash escape character. The following simple example illustrates the problem:
**without  the `-r` option**
```bash
$ echo '{"arguments":["\"\ud83d\udc4d\""]}' | (read INPUT; echo $INPUT) | jq -r .arguments[0]
parse error: Invalid numeric literal at line 1, column 27
```
**with the  `-r` option**
```bash
$ echo '{"arguments":["\"\ud83d\udc4d\""]}' | (read -r INPUT; echo $INPUT) | jq -r .arguments[0]
"👍"
```
In order to make sure that valid JSON is forwarded to the `openstack_cpi` ruby script, do not allow backslashes to escape any characters in the `cpi` shell script by using the `-r` option of the `read` command.
This seems to be a problem …
> Read the JSON line from the standard input in raw mode

- jobs/openstack_cpi/spec
- jobs/openstack_cpi/templates/cpi.json.erb
- src/bosh_openstack_cpi/spec/unit/bosh_release/jobs/cpi/templates/cpi.json.erb_spec.rb
- Can be specified under `blobstore.s3_{signature_version,region}` or
`agent.blobstore.s3_{signature_version,region}`
- Added testing for default values for the s3 blobstore properties
- Operator can specify AWS S3 region instead of the entire S3 host
[#111994203](https://www.pivotaltracker.com/story/show/111994203)
Signed-off-by: Lyle Franklin <lfranklin@pivotal.io>
> Allow operator to specify s3 signature version and region in manifest

- src/bosh_openstack_cpi/lib/cloud/openstack/cloud.rb
- src/bosh_openstack_cpi/lib/cloud/openstack/network_configurator.rb
- src/bosh_openstack_cpi/spec/unit/create_vm_spec.rb
- src/bosh_openstack_cpi/spec/unit/network_configurator_spec.rb
- if a vm is created with an already existing network port
the security groups of the port take precdence over
those specified for the vm
[#114099831](https://www.pivotaltracker.com/story/show/114099831)
Signed-off-by: Beyhan Veli <beyhan.veli@sap.com>
> Add security group ids to port creation

- src/bosh_openstack_cpi/lib/cloud/openstack/cloud.rb
- src/bosh_openstack_cpi/spec/unit/create_vm_spec.rb
tested successfully on Icehouse (deploying BOSH from bosh-init & CF from BOSH) (with boot_from_volume: true of course):
```
Using boot parms: `{:name=>"vm-5e498960-a16e-4d5c-9d7d-72fa26451306", :image_ref=>"792115dd-126a-4031-bdb0-48f3b5a41920", :flavor_ref=>"c4f75bdb-a283-4b7e-829c-ddd6f1edcf23", :key_name=>"cf-keypair2", :security_groups=>["default", "cf-private", "bosh"], :os_scheduler_hints=>nil, :nics=>[{"net_id"=>"d261123e-3d69-41b0-a74b-34af85cb677f", "v4_fixed_ip"=>"192.168.0.2"}], :config_drive=>false, :user_data=>"{\"registry\":{\"endpoint\":\"http://127.0.0.1:6901\"},\"server\":{\"name\":\"vm-5e498960-a16e-4d5c-9d7d-72fa26451306\"},\"networks\":{\"private\":{\"cloud_properties\":{\"net_id\":\"d261123e-3d69-41b0-a74b-34af85cb677f\"},\"default\":[\"dns\",\"gateway\"],\"dns\":[\"xx …
```
> use block_device_mapping_v2 instead of deprecated block_device_mapping

- jobs/openstack_cpi/templates/cpi.erb
[#119609491](https://www.pivotaltracker.com/story/show/119609491)
Signed-off-by: Felix Riegger <felix.riegger@sap.com>
> Use `exec` to avoid second bash process

- packages/bosh_openstack_cpi/packaging
- packages/ruby_openstack_cpi/packaging
The original behavior would exit before printing out the human readable
error.
[#119500797](https://www.pivotaltracker.com/story/show/119500797)
> Don't sub shell and use set -e -x in packaging scripts

- src/bosh_openstack_cpi/lib/cloud/openstack/cloud.rb
- src/bosh_openstack_cpi/spec/unit/cloud_spec.rb
The stemcell comes with the "hypervisor" attribute but glance expects
"hypervisor_type" instead.
[#121565957](https://www.pivotaltracker.com/story/show/121565957)
Signed-off-by: Mauro Morales <mamorales@suse.com>
fixes #39
> Fix stemcell hypervisor_type property

- src/bosh_openstack_cpi/Gemfile
- src/bosh_openstack_cpi/Gemfile.lock
- src/bosh_openstack_cpi/lib/cloud/openstack/cloud.rb
- src/bosh_openstack_cpi/lib/cloud/openstack/helpers.rb
- src/bosh_openstack_cpi/lib/cloud/openstack/openstack.rb
- src/bosh_openstack_cpi/spec/integration/image_spec.rb
- src/bosh_openstack_cpi/spec/integration/spec_helper.rb
- src/bosh_openstack_cpi/spec/integration/volume_spec.rb
- src/bosh_openstack_cpi/spec/spec_helper.rb
- src/bosh_openstack_cpi/spec/unit/cloud_spec.rb
- src/bosh_openstack_cpi/spec/unit/create_disk_spec.rb
- src/bosh_openstack_cpi/spec/unit/create_stemcell_spec.rb
- src/bosh_openstack_cpi/spec/unit/delete_stemcell_spec.rb
- src/bosh_openstack_cpi/spec/unit/openstack_spec.rb
- This allows the CPI to interact with Image (Glance) and Volume (Cinder) v2 APIs
- If the OpenStack environment doesn't support V2, the CPI automatically falls back to V1
- Introduces WebMock as a test dependency to force the OpenStack gem into Image/Volume V1 mode even if the environment supports V2
- Removes support for image[:copy_from] which allowed users to specify a remote URL for a stemcell as this feature doesn't exist in Glance V2
- Confirmed with Marco that this feature was never used by BOSH
- We added a temporary monkeypatch to fog-openstack which can be removed once
https://github.com/fog/fog-openstack/pull/170 is merged
- Use human-readable image names
- The image name is cosmetic, we always perform lookups based on image IDs
- …
> Add support for Image and Volume V2 services

- ci/pipelines/certify-stemcell/tasks/deploy-director.yml
- ci/pipelines/certify-stemcell/tasks/deploy-dummy-release-multiple-manual-networks.yml
- ci/pipelines/certify-stemcell/tasks/deploy-dummy-release.yml
- ci/pipelines/certify-stemcell/tasks/deploy-old-director.yml
- ci/pipelines/certify-stemcell/tasks/generate-certification.yml
- ci/pipelines/certify-stemcell/tasks/teardown-director.yml
- ci/pipelines/certify-stemcell/tasks/teardown.yml
- ci/pipelines/certify-stemcell/tasks/test-upgrade.yml
- ci/tasks/build-candidate.yml
- ci/tasks/cleanup.yml
- ci/tasks/deploy-dynamic-networking.yml
- ci/tasks/deploy-manual-networking.yml
- ci/tasks/promote-candidate.yml
- ci/tasks/publish-api-calls.yml
- ci/tasks/run-dynamic-networking-bats.yml
- ci/tasks/run-lifecycle.yml
- ci/tasks/run-manual-networking-bats.yml
- ci/tasks/teardown-director.yml
Concourse standalone does not support the deprecated (?) `image:` syntax.
See https://github.com/concourse/concourse/issues/402
> Use image_resource: instead of image:

- jobs/openstack_cpi/spec
- jobs/openstack_cpi/templates/cpi.json.erb
- src/bosh_openstack_cpi/lib/cloud/openstack/cloud.rb
- src/bosh_openstack_cpi/spec/integration/integration_config.rb
- src/bosh_openstack_cpi/spec/integration/lifecycle_spec.rb
- src/bosh_openstack_cpi/spec/integration/volume_spec.rb
- src/bosh_openstack_cpi/spec/unit/bosh_release/jobs/cpi/templates/cpi.json.erb_spec.rb
- src/bosh_openstack_cpi/spec/unit/create_disk_spec.rb
The disk type is determined in this order (descreasing priority):
- disk_pools.cloud_properties.type
- global_config.openstack.default_volume_type
- default type for entire Cinder installation
This allows the Operator to specify a different default type per Director without
needing permission to change the default type for the entire Cinder installation.
Signed-off-by: Brian Cunnie <bcunnie@pivotal.io>
[#135146373](https://www.pivotaltracker.com/story/show/135146373)
Signed-off-by: Chris Dutra <cdutra@pivotal.io>
> add 'default_volume_type' to global CPI config

- src/bosh_openstack_cpi/lib/cloud/openstack/cloud.rb
- src/bosh_openstack_cpi/lib/cloud/openstack/manual_network.rb
- src/bosh_openstack_cpi/lib/cloud/openstack/network.rb
- src/bosh_openstack_cpi/lib/cloud/openstack/network_configurator.rb
- src/bosh_openstack_cpi/spec/unit/create_vm_spec.rb
- src/bosh_openstack_cpi/spec/unit/manual_network_spec.rb
- src/bosh_openstack_cpi/spec/unit/network_configurator_spec.rb
This PR adds support for vms with a shared_vip.
The main usecase for this is using the [keepalived job](https://github.com/cloudfoundry-incubator/haproxy-boshrelease/tree/master/jobs/keepalived) from the haproxy release, to have vip shared between to haproxy instances using vrrp.
Some additional resources about this usecase:
- [highly available vips on openstack](https://blog.codecentric.de/en/2016/11/highly-available-vips-openstack-vms-vrrp/)
- [Allowed address pairs openstack api docs](https://specs.openstack.org/openstack/neutron-specs/specs/api/allowed_address_pairs.html)
- [fog allowed_address_pair example](https://github.com/fog/fog-openstack/blob/master/examples/network/network_add_port.rb#L19-L20)
Unit tested passed, will now test on our OpenStack, but wanted to already make to PR …
> shared_vip support for vrrp using allowed_address_pairs

- src/bosh_openstack_cpi/lib/cloud/openstack/availability_zone_provider.rb
- src/bosh_openstack_cpi/spec/unit/availability_zone_provider_spec.rb
- src/bosh_openstack_cpi/spec/unit/create_vm_spec.rb
If there are different AZs for disks and/or VMs we list all disk ids
with corresponding AZs explicitly.
Additionally, we provide a hint for 'openstack.ignore_server_availability_zone'
in case the user uses different AZs by intent.
[#156221894](https://www.pivotaltracker.com/story/show/156221894)
> Better error message in case of different AZs for disks and/or VMs

- config/blobs.yml
- packages/ruby_openstack_cpi/packaging
- packages/ruby_openstack_cpi/spec
Reverts cloudfoundry-incubator/bosh-openstack-cpi-release#144
ruby 2.5.1 breaks our cpi
> Revert "Bump packages"

- .zuul.yaml
We hope to move all of outside periodic jobs back to OpenLab
projects.yaml, so that we can plan the periodic testing resource
usage amount for OpenLab and avoid periodic jobs define confusion
in different project branch maintaining policy. Periodic jobs will
be moved to theopenlab/openlab-zuul-jobs#479 and will be triggered
at UTC-0 04:00 and 16:00 of everyday.
Related-Bug: theopenlab/openlab#173
> Move periodic jobs back to OpenLab

- ci/pipeline.yml
- ci/tasks/run-dynamic-networking-bats.sh
- ci/tasks/run-dynamic-networking-bats.yml
- ci/tasks/run-manual-networking-bats.sh
- ci/tasks/run-manual-networking-bats.yml
CCK tests can't be run on centos stemcells at the moment.
This change allows that centos tests skip the cck suite, but it will
still run in ubuntu-based stemcells.
> Add cck tests skipping for centos vms

- packages/bosh_openstack_cpi/packaging
- packages/bosh_openstack_cpi/pre_packaging
bundler stopped picking up some cli flags and some env vars. there have
been warnings around this but we do not see them when the create-env
succeeds. It wasn't caught in CI since the CI environment is not
internetless. In that case bundler was still able to reach out to get the
gems that were already present locally (which it ignored because it
ignored the cli flags)
fixes:
```
Finished installing CPI (00:03:11)
Cleaning up rendered CPI jobs... Finished (00:00:00)
Error getting CPI info:
Executing external CPI command: '/home/tempest-web/.bosh/installations/22a68df8-5b95-4b3c-41a4-4f2dd8dab4e7/jobs/openstack_cpi/bin/cpi':
Running command: '/home/tempest-web/.bosh/installations/22a68df8-5b95-4b3c-41a4-4f2dd8dab4e7/jobs/openstack_cpi/bin/cpi', stdout: '', stderr: 'bundler: failed to load …
```
> Fix broken offline environment create-env

- packages/bosh_openstack_cpi/packaging
- src/bosh_openstack_cpi/Gemfile.lock
We now specify BUNDLER_VERSION to prevent bundler from trying to install the version specified by BUNDLED WITH in the Gemfile.lock. Since we use the bundler from the ruby package, these versions are not likely to match.
This does not cause it to error in internetless environments, but it does hang for a long time before timing out and simply using the current bundler.
---
The Gemfile.lock was in a bad state causing this error:
`Could not find ipaddress-0.8.3 in locally installed gems`
which we are seeing in internetless environments.
> Fixes for running the cpi in an internetless environment

- ci/templates/jobs/openstack_cpi/spec.erb
- jobs/openstack_cpi/spec
- jobs/openstack_cpi/templates/cpi.json.erb
- src/bosh_openstack_cpi/spec/unit/bosh_release/jobs/cpi/templates/cpi.json.erb_spec.rb
The BOSH agent reads its blobstore settings from the metadata API endpoint (or equivalent) for its VM within the IaaS. If the blobstore settings are not set in the `env.bosh.blobstores` property, it will fallback to the top-level `blobstore` property in the metadata.
However, in modern configurations, the Director always sends the blobstore settings as part of the environment hash. Additionally, the Director does redaction of credentials in the environment hash when the signed URLs blobstore feature is enabled. This redaction is not applied to the top-level `blobstore` property in the metadata because that is generated solely by the CPI.
Rather than updating each CPI to know about the signed URL feature, we are instead removing the `blobstore` properties from the CPI. This will ensure …
> Remove blobstore info from IaaS metadata endpoints

- ci/tasks/deploy-dynamic-networking.sh
- ci/tasks/deploy-manual-networking.sh
This component is being removed from BOSH itself.
See https://github.com/cloudfoundry/bosh/pull/2501
> Remove PowerDNS references

- ci/tasks/run-lifecycle.sh
Unintentionally removed this, but the script needs it. This commit restores this essential variable.
> Restores local script variable

- src/bosh_openstack_cpi/lib/cloud/openstack/stemcell_creator.rb
- src/bosh_openstack_cpi/spec/unit/stemcell_creator_spec.rb
Hello,
based on the last pull request from: https://github.com/cloudfoundry/bosh-openstack-cpi-release/pull/280, 
I have added the property hw_vif_multiqueue_enabled, to enable the multiqueue feature to the network based on virtio, with this will complement the full virtio support.
For any questions or requirements, please let me know.
Thanks
David
> Adding multiqueue support for Virtio to the stemcell

- .github/dependabot.yml
- .github/workflows/go.yml
- .github/workflows/ruby.yml
- .golangci.yml
This PR incorporate feedback from https://github.com/cloudfoundry/bosh-openstack-cpi-release/pull/290#issuecomment-2436147678 
In addition to some details:
- add dependabot.yml to find any outdated GitHub Actions
- add .golangci.yml increasing the timeout to 3m for the windows-runners
-  For the go work flow: replace shell steps with separate unit and integration tests
- Make the ruby and go workflows run only when changes are made into the corresponding source folders
- Enable workflow_dispatch to allow manual triggering of the workflow actions
- Enable on-push workflows only on the master branch to avoid multiple redundant runs on a pull request
> Enhance Github Workflows

- ci/tasks/teardown-director.yml
The version-semver resource is no longer supplied, and isn't used by the script that this task runs, so we need to remove the resource.
> Fixes teardown-director task

- ci/pipeline.yml
With the move of the Openstack cluster to a new datacenter, it looks like two hours is sometimes just barely not enough time for the tests to complete. This commit increases the task timeout to three hours.
> Increases timeouts

- ci/pipeline.yml
This repo uses gitlfs, so we need to pass the private key to the CVE check task in order to compare current with previous version.
> Set git private key for CVE check

- ci/terraform/ci/lifecycle/versions.tf
- ci/terraform/ci/modules/lifecycle/versions.tf
When running terraform destroy with the 3.0.x version line, we are seeing terraform only destroying key pair resources, and not other things like network, security group, etc.
> Attempt to pin back Terraform to 2.1.x

- ci/pipeline.yml
This commit
1) Makes the initial Terraform Apply 'put' to the terraform resource not
explode because the tfstate file doesn't exist.
2) MAYBE resolves the "Workspace not empty" problem on the Terraform
Destroy 'put' to the Terraform resource.
NOTE:
I have no idea why this change resolves #1. I don't know if 'lifecycle' is a reserved word somewhere in the guts of Terraform, if the GCS storage adapter fails when env names and/or prefixes are too short, or if there must be hyphens in an env name and/or prefix. All I DO know is that I've had two runs in a row where the resource correctly started from a bucket that didn't have the tfstate file it was looking for and created all the resources it was instructed to.
I also do not know if this actually resolves #2, or if I've just gotten lucky …
> Makes Terraform resource work correctly

- ci/pipeline.yml
- ci/tasks/terraform-apply-lifecycle.sh
- ci/tasks/terraform-apply-lifecycle.yml
- ci/tasks/terraform-destroy-lifecycle.sh
- ci/tasks/terraform-destroy-lifecycle.yml
This PR does the following big things:
1) Switches away from the "nimbus" tag to the "openstack" tag for all tagged Tasks and Resources. We're doing this because the Nimbus workers are pretty unreliable, and also because we have multiple 'nimbus' workers, but a _single_ 'openstack' worker which massively reduces the time spent waiting for volume transfers.
2) Updates the 'lifecycle' Job to stop using the Concourse Terraform Resource and start using a pair of simple scripts to drive Terraform. For details about why this change is being made, please read the commit message whose headline is 'Switches away from Terraform Resource to script'.
One should also note that this is a total replacement of PR #304. That PR only appeared to make things work reliably. They did not actually work …
> Switch from terraform resource for lifecycle job, as well as switching to the "openstack" tag for many resources and tasks

- ci/pipeline.yml
- ci/tasks/terraform-apply-bats-manual.sh
- ci/tasks/terraform-apply-bats-manual.yml
- ci/tasks/terraform-destroy-bats-manual.sh
- ci/tasks/terraform-destroy-bats-manual.yml
This commit moves the bats-ubuntu-manual Job to the same sort of terraform apply/destroy script that's working very well for the lifecycle Job.
Why are we doing this? Because the last six runs of the lifecycle Job have all succeeded, whereas the last six runs of the bats-ubuntu-manual Job have failed due to Terraform "workspace" errors about half of the time. Moving to this script seems to get rid of any obvious usage of the Terraform "workspace" stuff, which seems to give our Builds a much, much higher success rate. (The fact that we don't need to transfer anything to or from GCS with this way of doing things is just a nice bonus.)
> Moves bats-ubuntu-manual Job to Terraform script

- ci/tasks/convert-terraform-output-to-mostly-json.awk
- ci/tasks/terraform-apply-bats-manual.sh
- ci/tasks/terraform-apply-lifecycle.sh
This commit should correctly handle the 'tolist' construction in the output from the 'terraform output' command. That construction is a bit too complex for my 'sed' skills, so I've fallen back on my crummy 'awk' skills to provide a replacement to the inline 'sed'.
I am bad at 'awk', so the 'awk' program definitely could be improved, but it's fit for its current limited purpose.
> Handle 'tolist' Terraform construction

- packages/openstack_cpi_golang/spec
We noticed that we incompletely package the vendored go packages, in contrast to how it is done in [bosh-google-cpi-release](https://github.com/cloudfoundry/bosh-google-cpi-release/blob/master/packages/bosh-google-cpi/spec) for example. This forced the runtime processes to re-download the vendored packages, which is not expected. This PR fixes this behaviour.
> prevent re-fetching of vendored go packages due to them being incompletely packaged
